a2e:
	g++ -g -Wall -I. -o main ./main.cpp ./ui/interface.cpp ./ui/tui/tui.cpp ./util/helper.cpp ./user_context/user_context.cpp

a2e_buggy:
	g++ -g -Wall -Wextra -pedantic -Werror -I. -o main ./main.cpp ./ui/interface.cpp ./ui/tui/tui.cpp ./util/helper.cpp ./user_context/user_context.cpp